name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Unit Tests
      run: dotnet test tests/unit/ --no-build --verbosity normal
    - name: Run Integration Tests
      run: dotnet test tests/integration/ --no-build --verbosity normal

  performance-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Run Performance Tests
      run: dotnet run --project tests\performance\OpenEchoSystem.GuardClauses.PerformanceTests.csproj --configuration Release

  docs-and-package:
    runs-on: ubuntu-latest
    needs: [build-and-test, performance-tests]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Install DocFX
      run: dotnet tool install -g docfx
    - name: Build Documentation
      run: docfx docs/docfx.json
    - name: Pack NuGet package
      run: dotnet pack src/OpenEchoSystem.GuardClauses.csproj -c Release -o ./nuget_packages --no-build
    - name: Publish NuGet package
      run: dotnet nuget push ./nuget_packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json